### ISSUE TITLE
Issue with Torque.h file

### ISSUE THREAD

**Issue by waseemrehman192** [guzhaoyuan/MaxonEpos2#3]
Hi,

I have compiled the code for Maxon Motor Wrapper and constantly getting the following error:

/home/user/EPOSC_ws/src/MaxonEpos2/src/controller3.cpp:10:43: fatal error: epos2/Torque2.h: No such file or directory
 #include "epos2/Torque2.h" // service file
compilation terminated.
/home/user/EPOSC_ws/src/MaxonEpos2/src/controller2.cpp:10:42: fatal error: epos2/Torque.h: No such file or directory
 #include "epos2/Torque.h" // service file

Could you suggest any resolution to this error? I couldn't find Torque.h, Torque2.h files in the code repository.

Regards,

**Comment by guzhaoyuan** [comment]
The "epos2/Torque2.h” is the header transformed from ROS message. I believe the problem is that the compiler compiled the controller3.cpp target before generating the headers.
The solution would be to add the following line in CMakeLists.txt.

add_dependencies(controller2 epos2_gencpp)
add_dependencies(controller3 epos2_gencpp)
